services:
  backend:
    image: mysite-backend
    container_name: mysite-backend
    pull_policy: never
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: runner
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env
    depends_on:
      - mongodb
    
  frontend:
    image: mysite-frontend
    container_name: mysite-frontend
    pull_policy: never
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 80:80

  mongodb:
    image: mongo
    container_name: mysite-mongodb
    volumes:
      - mongodb-data:/data/db
    # environment:
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: example
    env_file:
      - ./mongodb/.env
    
  mongo-express:
    image: mongo-express
    container_name: mysite-mongo-express
    ports:
      - 8081:8081
    # environment:
    #   ME_CONFIG_MONGODB_SERVER: mongodb
    #   ME_CONFIG_MONGODB_ADMINUSERNAME: root
    #   ME_CONFIG_MONGODB_ADMINPASSWORD: example
    env_file:
      - ./mongo-express/.env
    depends_on:
      - mongodb
    
volumes:
  mongodb-data: