services:
  backend:
    image: mysite-backend
    container_name: mysite-backend
    pull_policy: never
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: runner
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env
    
  frontend:
    image: mysite-frontend
    container_name: mysite-frontend
    pull_policy: never
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 80:80

  mongodb:
    image: mongo
    container_name: mysite-mongodb
    volumes:
      - mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    # env_file:
    #   - ./mongodb/.env
    
volumes:
  mongodb-data: